---
title: "testing_plots"
author: "Sarah Goldfarb"
date: "2026-01-30"
output: html_document
---

# Load the Required Packages
```{r Load Needed Libraries, include=FALSE}
packages <- c(
  "tidyverse",
  "gtsummary",
  "gt",
  "yaml",
  "rprojroot",
  "icd.data",
  "rlang"
)

install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

sapply(packages, install_if_missing)
rm(packages, install_if_missing)
```

# Load config to specify local paths
```{r Use YAML config to define values to R variables}
# Find project root
project_root <- find_root(rprojroot::has_dir("config"))

# Read YAML config
config <- yaml::read_yaml(file.path(project_root, "config", "config.yaml"))
global_config <- yaml::read_yaml(file.path(project_root, "config", "global_config.yaml"))

# Assign config values to R variables
tables_location <- config$tables_location
project_location <- config$project_location
site <- config$institution
site_time_zone <- config$time_zone
file_type <- config$file_type

# Cutoff for describing hospital as IMC capable
IMC_CAPABLE_CUTOFF <- global_config$imc_capable_cutoff

# Study start and end
STUDY_START <- as.POSIXct(global_config$study_start, tz=site_time_zone) # Start time
STUDY_END <- as.POSIXct(global_config$study_end, tz=site_time_zone) # End time

rm(config, global_config)
```

# Set global variables
```{r Set global variables}
TRIAGE_COLORS <- c(
    "ICU" = "red",
    "IMC" = "purple",
    "Ward" = "blue"
  )
```

# Create folders if needed
```{r Create folders if needed, include=FALSE}
#Create Sub Folders within Project Folder
# Check if the output directory exists; if not, create it
if (!dir.exists(paste0(project_location, "/private_tables"))) {
  dir.create(paste0(project_location, "/private_tables"))
}
if (!dir.exists(paste0(project_location, "/", site, "_project_output"))) {
  dir.create(paste0(project_location,"/", site, "_project_output"))
}
```

# Reading in data
```{r Read in cohort}
final_cohort <- read_csv(paste0(project_location, "/private_tables/one_encounter_per_pt_with_stratification.csv"), show_col_types=FALSE)
```

# Reformat variables for table display
```{r Reformat and reorder variables for table display}

reformat_cohort_cols <- function(df) {
  
  # Set order of triage location for foactoring
  traige_location_factors <- c("ICU", "IMC", "Ward")
  traige_location_imc_factors <- c("ICU (+)", "ICU (-)", "IMC", "Ward (+)", "Ward (-)")
  
  
  return(df |>
  mutate(
    # Format triage location
    triage_location_formatted = case_when(
      triage_location == "icu" ~ "ICU",
      triage_location == "stepdown" ~ "IMC",
      triage_location == "ward" ~ "Ward",
      TRUE ~ triage_location),
    # Set triage location as factor
    triage_location_formatted = factor(triage_location_formatted, levels = traige_location_factors),
    # Categorize triage location based on IMC availability
    traige_location_imc_avail = case_when(
      triage_location_formatted == "ICU" & imc_capable == 1 ~ "ICU (+)",
      triage_location_formatted == "ICU" ~ "ICU (-)",
      triage_location_formatted == "IMC" ~ "IMC",
      triage_location_formatted == "Ward" & imc_capable == 1 ~ "Ward (+)",
      triage_location_formatted == "Ward" ~ "Ward (-)",
      TRUE ~ triage_location_formatted
    ),
    # Set triage  as factor
    traige_location_imc_avail = factor(traige_location_imc_avail, levels = traige_location_imc_factors),
    # Factor race
    race_summary = factor(race_summary, levels=c("White", "Black or African American", "Asian", "Other")),
    # Factor last NIV device
    last_niv_device = factor(last_niv_device, levels=c("NIPPV", "High Flow NC")),
    # Factor type of ARF
    physiologic_type = factor(physiologic_type, levels=c("Hypoxic", "Hypercapnic", "Mixed", "Neither", "Undefined")),
    # Create binary variable if patient is female
    is_female = ifelse(tolower(sex_category) == "female", 1, 0),
    
    
    
    # Binary variable if patient died or discharged to hospice within 28 days
    death_hospice_28 = ifelse(
      (in_hosp_death == 1 | hospice == 1) &
      as.numeric(difftime(block_end_discharge, niv_start, units = "days")) <= 28,
      1, 0
    ),
    # Binary variable if patient died or discharged to hospice within 60 days
    death_hospice_60 = ifelse(
      (in_hosp_death == 1 | hospice == 1) &
      as.numeric(difftime(block_end_discharge, niv_start, units = "days")) <= 60,
      1, 0
    ),
    # Binary variable if patient had imv (set as NA if patient was DNI)
    imv = ifelse(is_dni, NA, ifelse(was_trach == 1 | was_intubated == 1, 1, 0)),
    # Binary variable if patient died or discharged to hospice at all
    death_hospice = ifelse(in_hosp_death == 1 | hospice == 1, 1, 0),
    
    # Reformat ICD code 9 vs 10
    diagnosis_code_format = case_when(
      str_detect(diagnosis_code_format, regex(paste0("icd.*9.*"), ignore_case = TRUE)) ~ "icd9",
      str_detect(diagnosis_code_format, regex(paste0("icd.*10.*"), ignore_case = TRUE)) ~ "icd10",
      TRUE ~ NA_character_
    ),
    # Reformat ICD codes to remove any non alphanumeric
    primary_diagnosis = gsub("[^A-Za-z0-9]", "", primary_diagnosis),
    
    # Create log10 scale for relevant variables
    los_pen_logged = log10(los_penalized),
    
    # Create a time variable based on presentation date
    time_x = as.Date(start_ed)
    
  ))
}

final_cohort <- reformat_cohort_cols(final_cohort)
```


```{r}
ggplot(final_cohort, aes(x = resp_support_free_days)) +
  geom_histogram(aes(y = after_stat(count)), bins = 30, fill="#aa2123") +
  theme_minimal()+
  labs(
  x="Days",
  y="Number of Patients",
  title="Number of respiratory-free days within the first 28 days of starting NIV",
  subtitle="Death/hospice within the first 28 days penalized to 0 days",
  )

```




```{r}
ggplot(final_cohort, aes(x = los_penalized)) +
  geom_histogram(aes(y = after_stat(count)), bins = 30, fill="#ffccf9") +
  theme_minimal()+
  labs(
  x="Days",
  y="Number of Patients",
  title="Length of Stay",
  subtitle="Death/hospice penalized to 99th percentile of distribution"
  )

```