---
title: "03_ARF_IMC_generate_local_coeff"
author: "Sarah Goldfarb"
date: "2026-01-13"
output: html_document
---

# Load the Required Packages
```{r Load Needed Libraries, include=FALSE}
packages <- c(
  "tidyverse",
  "yaml",
  "rprojroot",
  "stringr",
  "lmtest",
  "sandwich",
  "marginaleffects",
  "ordinal"
)

install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

sapply(packages, install_if_missing)
rm(packages, install_if_missing)
```

# Load config to specify local paths
```{r Use YAML config to define values to R variables}
# Find project root
project_root <- find_root(rprojroot::has_dir("config"))

# Read YAML config
config <- yaml::read_yaml(file.path(project_root, "config", "config.yaml"))
global_config <- yaml::read_yaml(file.path(project_root, "config", "global_config.yaml"))

# Assign config values to R variables
tables_location <- config$tables_location
project_location <- config$project_location
site <- config$institution
site_time_zone <- config$time_zone

file_type <- global_config$file_type
covariates <- global_config$covariates
outcomes_binary <- global_config$outcomes_binary
outcomes_counts <- global_config$outcomes_counts

rm(config, global_config)
```

# Create folders if needed
```{r Create folders if needed, include=FALSE}
#Create Sub Folders within Project Folder
# Check if the output directory exists; if not, create it
if (!dir.exists(paste0(project_location, "/private_tables"))) {
  dir.create(paste0(project_location, "/private_tables"))
}
if (!dir.exists(paste0(project_location, "/", site, "_project_output"))) {
  dir.create(paste0(project_location,"/", site, "_project_output"))
}
```

# Reading in data
```{r Read in cohort}
final_cohort <- read_csv(paste0(project_location, "/private_tables/one_encounter_per_pt_with_stratification.csv"), show_col_types=FALSE)
no_pandemic_cohort <- read_csv(paste0(project_location, "/private_tables/no_pandemic_one_encounter_per_pt_with_stratification.csv"), show_col_types=FALSE)

reformat_cohort_cols <- function(df) {
  
  # Set order of triage location for foactoring
  traige_location_factors <- c("ICU", "IMC", "Ward")
  traige_location_imc_factors <- c("ICU (+)", "ICU (-)", "IMC", "Ward (+)", "Ward (-)")
  
  
  return(df |>
  mutate(
    # Format triage location
    triage_location_formatted = case_when(
      triage_location == "icu" ~ "ICU",
      triage_location == "stepdown" ~ "IMC",
      triage_location == "ward" ~ "Ward",
      TRUE ~ triage_location),
    # Set triage location as factor
    triage_location_formatted = factor(triage_location_formatted, levels = traige_location_factors),
    # Categorize triage location based on IMC availability
    traige_location_imc_avail = case_when(
      triage_location_formatted == "ICU" & imc_capable == 1 ~ "ICU (+)",
      triage_location_formatted == "ICU" ~ "ICU (-)",
      triage_location_formatted == "IMC" ~ "IMC",
      triage_location_formatted == "Ward" & imc_capable == 1 ~ "Ward (+)",
      triage_location_formatted == "Ward" ~ "Ward (-)",
      TRUE ~ triage_location_formatted
    ),
    # Set triage  as factor
    traige_location_imc_avail = factor(traige_location_imc_avail, levels = traige_location_imc_factors),
    # Factor last NIV device
    last_niv_device = factor(last_niv_device, levels=c("NIPPV", "High Flow NC")),
    
    # Create binary variable if patient is female
    is_female = ifelse(tolower(sex_category) == "female", 1, 0),
    
    # Binary variable if patient had imv (set as NA if patient was DNI)
    imv = ifelse(is_dni, NA, ifelse(was_trach == 1 | was_intubated == 1, 1, 0)),
    
    # Binary variable if patient died or discharged to hospice at all
    death_hospice = ifelse(in_hosp_death == 1 | hospice == 1, 1, 0),
    
    first_hospital_id = factor(first_hospital_id),
    
    # Set code status as full/presumed full vs other
    code_status_full = case_when(
      is.na(code_status_category) ~ 1, # Presume full if no code status charted
      str_detect(tolower(code_status_category), "full") ~ 1,
      TRUE ~ 0),
    
    # Make year a factor
    year = as.factor(year),
    
    # Set cutoffs for SF
    sf_factor = factor(
      case_when(
        is.na(sf_value) ~ "Not present",
        sf_value > 250 ~ "> 250",
        sf_value > 200 ~ "> 200",
        sf_value > 150 ~ "> 150",
        TRUE ~ "<= 150"
      ),
      levels=c("Not present", "> 250", "> 200","> 150", "<= 150")
    ),
    
    # Set cutoffs for pH
    ph_factor = factor(
      case_when(
        is.na(ph_value) ~ "Not present",
        ph_value > 7.35 ~ "> 7.35",
        ph_value > 7.25 ~ "> 7.25",
        ph_value > 7.15 ~ "> 7.15",
        TRUE ~ "<= 7.15"
      ),
      levels=c("Not present", "> 7.35", "> 7.25", "> 7.15", "<= 7.15")
    )
    
  ))
}

final_cohort <- reformat_cohort_cols(final_cohort)
no_pandemic_cohort <- reformat_cohort_cols(no_pandemic_cohort)
```

```{r}
# Keep track of hospital information
hospital_data <- read_csv(paste0(project_location,"/", site, "_project_output/", site,"_hospital_data.csv"), show_col_types=FALSE)

no_pandemic_hospital_data <- read_csv(paste0(project_location,"/", site, "_project_output/sensitivity_analysis/", site,"_no_covid_hospital_data.csv"), show_col_types=FALSE)
```

```{r}

run_logit_models <- function(cohort_data, hosp_data){

  # Remove IMC patients and add indicator if admitted to ICU
  all_model_data <- cohort_data |> 
    filter(triage_location %in% c("icu", "ward")) |>
    mutate(icu_admission = ifelse(tolower(triage_location)=="icu", 1, 0))
  
    # Initialize the model coefficients dataframe
    model_coefficients <- data.frame(
      site = character(),
      hospital = character(),
      imc_capable = numeric(),
      academic_community = character(),
      outcome=character(),
      beta=numeric(),
      beta_error=numeric(),
      n_obs=integer(),
      p_value=numeric(),
      risk_difference=numeric(),
      risk_difference_error=numeric(),
      risk_difference_p=numeric(),
      stringsAsFactors = FALSE
    )
  
  # Iterate over each binary outcome of interest
  for(outcome in outcomes_binary){
    model_equation <- paste0(outcome, " ~ icu_admission + ", paste(covariates, collapse = " + "))
    cat("\n---------------------\n")
    cat("Cohort: ", deparse(substitute(cohort_data)), "\n")
    cat(paste0("Running models using equation:\n", model_equation, "\n\n"))
    
    # Iterate over each hospital at this local site
    for(i in seq_len(nrow(hosp_data))){
      cat(paste0("   > Running for: ",hosp_data$first_hospital_id[i], "...\n   "))
      
      # Only select rows at the given hospital
      model_data <- all_model_data |> 
        filter(first_hospital_id == hosp_data$first_hospital_id[i])

      # Run logistic regression
      model_1 <- glm(
        model_equation,
        data=model_data,
        family=binomial
        )
      
      # Marginal effects
      marginal_effects <- avg_slopes(
        model=model_1,
        newdata = datagrid(
          model=model_1,
          grid_type="counterfactual",
          icu_admission=c(0,1),
          variables="icu_admission"
          )
        ) |>
        filter(term=="icu_admission")
      
      model_coefficients <- model_coefficients |>
        add_row(
          site = site,
          hospital = hosp_data$first_hospital_id[i],
          imc_capable = hosp_data$imc_capable[i],
          academic_community = hosp_data$academic_community[i],
          outcome=outcome,
          beta=coeftest(model_1)["icu_admission","Estimate"],
          beta_error=coeftest(model_1)["icu_admission","Std. Error"],
          n_obs=nobs(model_1),
          p_value=coeftest(model_1)["icu_admission","Pr(>|z|)"],
          risk_difference=marginal_effects$estimate,
          risk_difference_error=marginal_effects$std.error,
          risk_difference_p=marginal_effects$p.value
        )
      
      cat(paste0(" Complete!\n"))
    }
  }
  return(model_coefficients)
}


```

```{r}
model_coefficients <- run_logit_models(final_cohort, hospital_data)
no_pandemic_model_coefficients <- run_logit_models(no_pandemic_cohort, no_pandemic_hospital_data)
```

```{r}
write_csv(model_coefficients, file.path(paste0(project_location, "/", site,"_project_output/"), paste0(site,"_model_coefficients.csv")))
write_csv(no_pandemic_model_coefficients, file.path(paste0(project_location, "/", site,"_project_output/sensitivity_analysis/"), paste0(site,"_no_covid_model_coefficients.csv")))
```

```{r}
run_prop_odds_models <- function(cohort_data, hosp_data){
  
  # Remove IMC patients and add indicator if admitted to ICU
  all_model_data <- cohort_data |> 
    filter(triage_location %in% c("icu", "ward")) 
  
  # Set the cutoff for length of stay
  max_days_los <- ceiling(max(all_model_data$los_penalized))
  
  # Create outcome variables
  all_model_data <- all_model_data |>
    mutate(resp_support_free_days = factor(floor(resp_support_free_days),
                                           levels=as.character(0:28),
                                           ordered=TRUE),
           
           los_ordinal = cut(
             los_penalized,
             breaks = c(seq(-0.5, max_days_los + 0.5, by = 1)),
             labels = c(as.character(0:max_days_los)),
             right = TRUE,
             ordered_result = TRUE
    )

           ) |>
    mutate(icu_admission = ifelse(tolower(triage_location)=="icu", 1, 0))
  
    # Initialize the model coefficients dataframe
    model_coefficients <- data.frame(
      site = character(),
      hospital = character(),
      imc_capable = numeric(),
      academic_community = character(),
      outcome=character(),
      beta=numeric(),
      beta_error=numeric(),
      n_obs=integer(),
      p_value=numeric(),
      # May need to add some stuff for marginal effects here
      stringsAsFactors = FALSE
    )
    
    # Iterate over each count outcome
    for(outcome in outcomes_counts){
      
      model_equation <- paste0(outcome, " ~ icu_admission + ", paste(covariates, collapse = " + "))
      
      cat("\n---------------------\n")
      cat("Cohort: ", deparse(substitute(cohort_data)), "\n")
      cat(paste0("Running models using equation:\n", model_equation, "\n\n"))
      
      # Iterate over each hospital at this local site
      for(i in seq_len(nrow(hosp_data))){
        cat(paste0("   > Running for: ",hosp_data$first_hospital_id[i], "...\n   "))
        
        # Only select rows at the given hospital
        model_data <- all_model_data |> 
          filter(first_hospital_id == hosp_data$first_hospital_id[i])
        
        # Run culmulative logistic regression
        model_2 <- clm(
          model_equation,
          data=model_data,
          link="logit"
          )
        
        model_coefficients <- model_coefficients |>
          add_row(
            site = site,
            hospital = hosp_data$first_hospital_id[i],
            imc_capable = hosp_data$imc_capable[i],
            academic_community = hosp_data$academic_community[i],
            outcome=outcome,
            beta=coeftest(model_2)["icu_admission","Estimate"],
            beta_error=coeftest(model_2)["icu_admission","Std. Error"],
            n_obs=nobs(model_2),
            p_value=coeftest(model_2)["icu_admission","Pr(>|t|)"]
            # May need to add some stuff for marginal effects here
        )
        
        
        cat(paste0(" Complete!\n"))
      }
    }
  return(model_coefficients)
}
```

```{r}
model_coefficients_prop_odds <-run_prop_odds_models(final_cohort, hospital_data)
no_pandemic_model_coefficients_prop_odds <-run_prop_odds_models(no_pandemic_cohort, no_pandemic_hospital_data)
```

```{r}
write_csv(model_coefficients_prop_odds, file.path(paste0(project_location, "/", site,"_project_output/"), paste0(site,"_model_coefficients_prop_odds.csv")))
write_csv(no_pandemic_model_coefficients_prop_odds, file.path(paste0(project_location, "/", site,"_project_output/sensitivity_analysis/"), paste0(site,"_no_covid_model_coefficients_prop_odds.csv")))
```

# OLD, includes marginal effects for counting outcomes
```{r}
# # Proportional odds for continuous/count variables
# model_data_2 <- final_cohort |> 
#   filter(triage_location %in% c("icu", "ward")) |>
#   mutate(resp_support_free_days = factor(floor(resp_support_free_days),
#                                          levels=as.character(0:28),
#                                          ordered=TRUE)) |>
#   mutate(icu_admission = ifelse(tolower(triage_location)=="icu", 1, 0))
# 
# model_2 <- clm(
#   resp_support_free_days ~ icu_admission + age_at_admission + is_female,
#   data=model_data_2,
#   link="logit"
# )
# 
# p_2 <- avg_predictions(model_2, by="icu_admission")
# 
# p_3 <- avg_predictions(model_2, 
#                        newdata=datagrid(
#                          model=model_2,
#                           grid_type="counterfactual",
#                           icu_admission=c(0,1),
#                           variables="icu_admission"
#                        ),
#                        by="icu_admission")
# 
# summary(model_2)

```
