---
title: "05_ARF_IMC_generate_summary_coeff"
author: "Sarah Goldfarb"
date: "2026-01-13"
output: html_document
---

# Load the Required Packages, specify local paths
```{r Load Needed Libraries, include=FALSE}
packages <- c(
  "tidyverse",
  "yaml",
  "rprojroot",
  "metafor",
  "meta",
  "ggplot2"
)

install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

sapply(packages, install_if_missing)
rm(packages, install_if_missing)

# Find project root
project_root <- find_root(rprojroot::has_dir("config"))

# Read YAML config
config <- yaml::read_yaml(file.path(project_root, "config", "config.yaml"))
global_config <- yaml::read_yaml(file.path(project_root, "config", "global_config.yaml"))

if(config$institution != "Hopkins"){
  stop("you have completed running all of the files!")
}

# Assign config values to R variables
project_location <- config$project_location
outcomes_binary <- global_config$outcomes_binary
outcomes_counts <- global_config$outcomes_counts

rm(config, global_config)
```

# Define sites, outcomes
```{r}

# Sites and outcomes
sites <- c("Hopkins")

# Output directory for global model outcomes
if (!dir.exists(paste0(project_location, "/global_model_outputs"))) {
  dir.create(paste0(project_location, "/global_model_outputs"))}
global_out_dir <- file.path(project_location, "global_model_outputs/")

```

```{r}
# Get site folder path
# cohort_name can be set as "_no_covid"
# model_run can be logit, prop_odds, or icu_adm
site_export_dir <- function(site, model_run, cohort_name="") {
  
  if(model_run == "logit"){
    file_name <- "_logit_model_coefficients.csv"
  }
  else if (model_run == "prop_odds"){
    file_name <- "_prop_odds_model_coefficients.csv"
  }
  else{
    file_name <- "_icu_adm_model_coefficients.csv"
  }
  
  return(file.path(paste0(project_location, 
            site, 
            "_project_output/",
            "local_model_outputs/",
            site,
            cohort_name,
            file_name)))
}

site_export_dir_marginal_effects <- function(site, hospital, cohort_name="") {
  
    return(file.path(paste0(project_location, 
            site, 
            "_project_output/",
            "local_model_outputs/",
            site,
            cohort_name,
            "_resp_support_free_days_",
            hospital,
            "_marginal_effects.csv")))
  
}

```

# Reading in local site results, compiling into one df
```{r}

model_coefficients_binary <- data.frame(
    site = character(),
    hospital = character(),
    imc_capable = numeric(),
    academic_community = character(),
    outcome=character(),
    beta=numeric(),
    beta_error=numeric(),
    n_obs=integer(),
    p_value=numeric(),
    risk_difference=numeric(),
    risk_difference_error=numeric(),
    risk_difference_p=numeric(),
    prediction_icu=numeric(),
    prediction_icu_error=numeric(),
    prediction_icu_p=numeric(),
    prediction_ward=numeric(),
    prediction_ward_error=numeric(),
    prediction_ward_p=numeric(),
    stringsAsFactors = FALSE
  )
  
  # Initialize the model coefficients dataframe
  model_coefficients_counts <- data.frame(
    site = character(),
    hospital = character(),
    imc_capable = numeric(),
    academic_community = character(),
    outcome=character(),
    beta=numeric(),
    beta_error=numeric(),
    n_obs=integer(),
    p_value=numeric(),
    stringsAsFactors = FALSE
    )
  
  model_coefficients_icu_adm <- data.frame(
    site = character(),
    hospital = character(),
    imc_capable = numeric(),
    academic_community = character(),
    outcome=character(),
    n_obs=integer(),
    prediction_icu_adm=numeric(),
    prediction_icu_error=numeric(),
    prediction_icu_p=numeric(),
    stringsAsFactors = FALSE
  )

# Iterate over each site, load in model outputs
for(s in sites){
  
  model_coefficients_binary <- model_coefficients_binary |>
    add_row(
      read_csv(site_export_dir(site=s, model_run="logit"), show_col_types=FALSE)
    )
  
  
  model_coefficients_counts <- model_coefficients_counts |>
    add_row(
      read_csv(site_export_dir(site=s, model_run="prop_odds"), show_col_types=FALSE)
    )
  
  model_coefficients_icu_adm <- model_coefficients_icu_adm |>
    add_row(
      read_csv(site_export_dir(site=s, model_run="icu_adm"), show_col_types=FALSE)
    )
}
  
# Ensure correct data type
model_coefficients_binary$imc_capable <- factor(model_coefficients_binary$imc_capable)
model_coefficients_counts$imc_capable <- factor(model_coefficients_counts$imc_capable)
model_coefficients_binary$academic_community <- factor(model_coefficients_binary$academic_community)
model_coefficients_counts$academic_community <- factor(model_coefficients_counts$academic_community)
```

# Helper function for plotting and formatting p value symbols
```{r}
plot_ORs <- function(df){
  forest_log_odds <- df |>
    mutate(
      odds_ratio = exp(beta),
      ci_low  = exp(beta - 1.96 * beta_error),
      ci_high = exp(beta + 1.96 * beta_error),
      dot_size = scales::rescale(n_obs, to=c(5,10)),
      # Order it so that they go in order from lowest to highest odds ratios for display
      hospital_num = fct_reorder(as.factor(hospital), odds_ratio)
    ) |>
    select(hospital_num, imc_capable, academic_community,odds_ratio, ci_low, ci_high, dot_size)
  
  p <- ggplot(forest_log_odds, aes(x = odds_ratio, y = hospital_num)) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_errorbarh(
    aes(xmin = ci_low, xmax = ci_high),
    height = 0
  ) +
  geom_point(
    aes(size = dot_size,
        color=imc_capable,
        shape=academic_community)
  ) +
  #guides(size="none")+
  scale_x_log10() +
  scale_size_continuous(
      breaks = quantile(forest_log_odds$dot_size, probs = c(0.25, 0.75)),
      labels = c("Fewer Patients", "More Patients")
  ) +
  scale_color_manual(
    values=c("0" = "#F81212", "1" = "#00BFCF"),
    labels=c("0" = "Incapable", "1" = "Capable")
  ) +
  scale_shape_manual(
    values=c("academic" = 15, "community" =17),
    labels=c("academic" = "Academic", "community" = "Community")
  ) +
  theme_minimal()+
  labs(
    x = "Odds Ratio (log scale)",
    y = "",
    color="IMC Capable",
    size = "Number of Patients",
    shape= "Academic or Community",
    title = case_when(
      outcome_binary == "death_hospice" ~ "Death/Discharge to Hospice",
      outcome_binary == "organ_failure_yn" ~ "Organ Failure",
      TRUE ~ outcome_binary),
    subtitle= paste0("Among sites: ", paste0(sites, collapse=", "))
  ) +
  theme(
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )
  
  print(p)

  ggsave(paste0(global_out_dir, outcome_binary,"_odds_ratios_by_hospital.jpg"), plot=p, width=7, height=5, dpi=300)
}

add_p_symbols <- function(df){
  return(
    df |>
      mutate(
        p_symb = case_when(
          p < 0.001 ~ "***",
          p < 0.01 ~ "**",
          p < 0.05 ~ "*",
          TRUE ~ "NS"
        )
      )
  )
}
```


# Binary outcomes
```{r}

meta_analyses_binary <- data.frame(
  outcome=character(),
  measure=character(),
  covariate=character(),
  estimate=numeric(),
  error=numeric(),
  p=numeric()
)

# Loop over each binary outcome
for (outcome_binary in outcomes_binary){
  
  # Subset to only outcome of interest
  model_coefficients <- model_coefficients_binary |>
    filter(outcome == outcome_binary)
  
  ### log odds ###
  log_odds <- rma(
    data=model_coefficients,
    yi=beta,
    sei=beta_error,
    method="REML",
    mods= ~ imc_capable + academic_community
  )
  
  meta_analyses_binary <- meta_analyses_binary |>
    add_row(
    outcome=outcome_binary,
    measure="log odds",
    covariate=rownames(log_odds$beta),
    estimate = log_odds$beta[,1],
    error = log_odds$se,
    p = log_odds$pval
  )
  
  # Call helper function to plot the ORs
  plot_ORs(model_coefficients)
  
  ### risk difference ###
  risk_diff <- rma(
    data=model_coefficients,
    yi=risk_difference,
    sei=risk_difference_error,
    method="REML",
    mods= ~ imc_capable + academic_community
  )
  
  meta_analyses_binary <- meta_analyses_binary |>
    add_row(
    outcome=outcome_binary,
    measure="risk difference",
    covariate=rownames(risk_diff$beta),
    estimate = risk_diff$beta[,1],
    error = risk_diff$se,
    p = risk_diff$pval
  )
  
  ### predicted values (ICU and ward) ###
  icu_pred <- rma(
    data=model_coefficients,
    yi=prediction_icu,
    sei=prediction_icu_error,
    method="REML",
    mods= ~ imc_capable + academic_community
  )
  meta_analyses_binary <- meta_analyses_binary |>
    add_row(
    outcome=outcome_binary,
    measure="icu predicted",
    covariate=rownames(icu_pred$beta),
    estimate = icu_pred$beta[,1],
    error = icu_pred$se,
    p = icu_pred$pval
  )
    
  ward_pred <- rma(
    data=model_coefficients,
    yi=prediction_ward,
    sei=prediction_ward_error,
    method="REML",
    mods= ~ imc_capable + academic_community
  )
  meta_analyses_binary <- meta_analyses_binary |>
    add_row(
    outcome=outcome_binary,
    measure="ward predicted",
    covariate=rownames(ward_pred$beta),
    estimate = ward_pred$beta[,1],
    error = ward_pred$se,
    p = ward_pred$pval
  )
  
}

# Clean R Workspace
rm(model_coefficients, log_odds, risk_diff, icu_pred, ward_pred)

# Add p symbols and remove intercept
meta_analyses_binary <- add_p_symbols(meta_analyses_binary |>
                                        filter(covariate != "intrcpt"))

write_csv(meta_analyses_binary, paste0(global_out_dir, "meta_analyses_binary.csv"))

```

# Count outcomes
```{r}
meta_analyses_counts <- data.frame(
  outcome=character(),
  covariate=character(),
  estimate=numeric(),
  error=numeric(),
  p=numeric()
)

# Loop over each count outcome
for (outcome_counts in outcomes_counts){
  
  # Subset to only outcome of interest
  model_coefficients <- model_coefficients_counts |>
    filter(outcome == outcome_counts)
  
  prop_odds <- rma(
    data=model_coefficients,
    yi=beta,
    sei=beta_error,
    method="REML",
    mods= ~ imc_capable + academic_community
  )
  
  meta_analyses_counts <- meta_analyses_counts |>
    add_row(
    outcome=outcome_counts,
    covariate=rownames(prop_odds$beta),
    estimate = prop_odds$beta[,1],
    error = prop_odds$se,
    p = prop_odds$pval
  )
}

# Clean R Workspace
rm(model_coefficients, prop_odds)

# Add p symbols and remove intercept
meta_analyses_counts <- add_p_symbols(meta_analyses_counts |>
                                        filter(covariate != "intrcpt"))


write_csv(meta_analyses_counts, paste0(global_out_dir, "meta_analyses_counts.csv"))
```

# Meta analysis for process outcome of ICU admission
```{r}
meta_analyses_icu_adm <- data.frame(
  outcome=character(),
  covariate=character(),
  estimate=numeric(),
  error=numeric(),
  p=numeric()
)

odds_icu_adm <- rma(
    data=model_coefficients_icu_adm, # No need to subset for outcome, since all one outcome
    yi=prediction_icu_adm,
    sei=prediction_icu_error,
    method="REML",
    mods= ~ imc_capable + academic_community
)

meta_analyses_icu_adm <- data.frame(
    outcome="ICU admission",
    covariate=rownames(odds_icu_adm$beta),
    estimate = odds_icu_adm$beta[,1],
    error = odds_icu_adm$se,
    p = odds_icu_adm$pval,
    row.names=NULL
  )

# Add p symbols and remove intercept
meta_analyses_icu_adm <- add_p_symbols(meta_analyses_icu_adm |>
                                        filter(covariate != "intrcpt"))


write_csv(meta_analyses_counts, paste0(global_out_dir, "meta_analyses_icu_admission.csv"))

```

# Create histograms of compiled predicted respiratory support free days
```{r}

marginal_effects_raw <- data.frame(
    group = numeric(),
    icu_admission = numeric(),
    estimate = numeric(),
    std.error = numeric(),
    statistic = numeric(),
    p.value = numeric(),
    s.value = numeric(),
    conf.low = numeric(),
    conf.high = numeric(),
    stringsAsFactors = FALSE
  )

# Get list of site-hospital pairs
site_hosp_pairs <- model_coefficients_counts |>
  select(site, hospital) |>
  distinct()

for(i in seq_len(nrow(site_hosp_pairs))){
  
  marginal_effects_raw <- marginal_effects_raw |>
    add_row(
      read_csv(site_export_dir_marginal_effects(site=site_hosp_pairs$site[i],
                                                hospital=site_hosp_pairs$hospital[i]),
               show_col_types=FALSE)
    )
}

# Ensure correct data type
marginal_effects_raw <- marginal_effects_raw |>
    mutate(group = factor(group,
                          levels=as.character(0:28),
                          ordered=TRUE),
           icu_admission = factor(as.character(icu_admission), levels=c("0", "1")))
```

```{r}
meta_analysis_resp_support <- marginal_effects_raw |>
  mutate(variance = (std.error)^2) |>
  select(group, icu_admission, estimate, variance) |>
  group_by(group, icu_admission) |>
  group_modify(~{
    
    fit <- rma.uni(yi = .x$estimate, vi = .x$variance, method = "REML")

    tibble(
      n_hosp = nrow(.x),
      pooled_estimate = as.numeric(fit$b[1]),
      pooled_se = as.numeric(fit$se[1]),
      ci_low = as.numeric(fit$ci.lb),
      ci_high = as.numeric(fit$ci.ub)
    )
  }) |>
  ungroup() |>
  rename(Days=group)

```

```{r}
resp_free_icu_histogram <- ggplot(meta_analysis_resp_support |> filter(icu_admission=="1"), aes(x = Days, y = pooled_estimate)) +
  geom_col(width = 1, fill="red") +
  theme_minimal() +
  labs(title="Predicted Number of Respiratory Support-Free Days (ICU)",
       y ="Proportion of Patients")

resp_free_icu_histogram

ggsave(
  filename = paste0(global_out_dir, "resp_free_icu_histogram.jpg"),
  plot = resp_free_icu_histogram,
  width = 7,
  height = 5,
  dpi = 300
)
```

```{r}
resp_free_ward_histogram <- ggplot(meta_analysis_resp_support |> filter(icu_admission=="0"), aes(x = Days, y = pooled_estimate)) +
  geom_col(width = 1, fill="blue") +
  theme_minimal() +
  labs(title="Predicted Number of Respiratory Support-Free Days (Ward)",
       y ="Proportion of Patients")

resp_free_ward_histogram

ggsave(
  filename = paste0(global_out_dir, "resp_free_ward_histogram.jpg"),
  plot = resp_free_ward_histogram,
  width = 7,
  height = 5,
  dpi = 300
)
```